s = input('Digite algo ')
print('A classe primitiva do digitado é: {}'.format(type(s)))
print('O valor digitado é composto só por letras? {}'.format(s.isalpha()))
print('O valor digitado é composto só por números? {}'.format(s.isnumeric()))
print('O valor digitado tem letras ou números? {}'.format(s.isalnum()))
print('O valor digitado é ASCII? {}'.format(s.isascii()))
print('O valor digitado é decimal? {}'.format(s.isdecimal()))
print('O valor digitado é um digito? {}'.format(s.isdigit()))
print('O valor digitado é  composto só por maiúsculas? {}'.format(s.isupper()))
print('O valor digitado é composto só por minúsculas? {}'.format(s.islower()))
print('O valor digitado é um espaço? {}'.format(s.isspace()))
print('O valor digitado é imprimível? {}'.format(s.isprintable()))
